version: '3.8'

services:
  nextjs:
    build:
      context: ./nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
    depends_on:
      - drupal
      - redis

  drupal:
    image: drupal:10
    ports:
      - "8080:80"
    volumes:
      - ./drupal:/var/www/html
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    ports:
      - "6379:6379"
